# workflow name
name: Hello World

# Execution timing
on:
  # Manual execution
  workflow_dispatch:

jobs:
  # job name
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  hello2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 2!"
