name: setup-terraform demo

on:
  workflow_dispatch:
  push:
    branches: [master]

defaults:
  run:
    working-directory: terraform

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Terraform fmt
        run: |
          pwd
          terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: |
          pwd
          terraform init

      - name: Terraform Validate
        run: |
          pwd
          terraform validate -no-color

      - name: Terraform Plan
        run: |
          pwd
          terraform plan -no-color
        continue-on-error: true
