name: setup-terraform demo

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
